### ISSUE TITLE
Odd behavior on text select

### ISSUE THREAD

**Issue by noizo** [extras-evolution/tinymce4-for-modx-evo#17]
Hi again.

There is something with text window when there is lots of text in it.
When i'm trying to select some text, whole window is being scrolled down very fast, making it impossible to select one line. Its working fine, if i put editor in fullscreen mode. Still there is a z-index glitch on content page tab, which is on top of editor window. 

Hard to explain.

Take a look on a video
http://take.ms/3UsPw

**Comment by Deesen** [comment]
Maybe a browser-issue? Have you tried several different browsers for testing?

**Comment by noizo** [comment]
Just did, seems like Safari issue.
Chromium and Firefox acts just fine.

**Comment by Deesen** [comment]
Cannot find anything related on google so I´m not sure we can solve it.

**Comment by noizo** [comment]
Well, leave scroll thing, take a look at page tab, that is shown above editor window.
It also appears in Chromium and FF

**Comment by Deesen** [comment]
This is related to Manager Theme "MODxCarbon" you use. In style.css line 1100:

```
.dynamic-tab-pane-control .tab-row .tab.selected {
  z-index:3
}
```

I don´t know why there is a z-index for .selected.

**Comment by noizo** [comment]
Weird. But thanks anyway.
CU :+1:
