### ISSUE TITLE
mini setting is not 100: width 

### ISSUE THREAD

**Issue by Dmi3yy** [extras-evolution/tinymce4-for-modx-evo#2]
http://take.ms/Oy1rj

**Comment by Deesen** [comment]
mini-theme is fixed to 200px height and 200px width and me, I thought this makes sense because of "mini" ?

**Comment by Dmi3yy** [comment]
i think width need 100%  
height is correct to fixed

## 

Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80

понедельник, 14 марта 2016 г. в 20:28, Deesen написал:

**Comment by Deesen** [comment]
You find it here https://github.com/extras-evolution/tinymce4-for-modx-evo/blob/master/assets/plugins/tinymce4/theme/theme.tinymce4.mini.inc.php#L33 or I do it later.
