### ISSUE TITLE
Wrong var name in bridge.tinymce4.inc.php

### ISSUE THREAD

**Issue by janniconl** [extras-evolution/tinymce4-for-modx-evo#27]
On r.112

```
        if (isset($this->pluginParams['styleFormats'])) {
            $styles_formats = explode('|', $this->pluginParams['styleFormats']);
```

Should be:

```
        if (isset($this->pluginParams['pluginStyleFormats'])) {
            $styles_formats = explode('|', $this->pluginParams['pluginStyleFormats']);
```

(So take the value from: pluginStyleFormats)

Otherwise the styles you've added to the plugin configuration are not loaded..

**Comment by janniconl** [comment]
While we're at it. I've changed ``bridge_style_formats()` function in the bridge file so it takes the styles in the config. If it is empty, it falls back to some default styles:

````
    // https://www.tinymce.com/docs/configure/content-formatting/#style_formats
    public function bridge_style_formats($selector) {
        // Set in plugin-configuration, format: Title,cssClass|Title2,cssClass
        if (isset($this->pluginParams['pluginStyleFormats'])) {
            $styles_formats = explode('|', $this->pluginParams['pluginStyleFormats']);
            foreach ($styles_formats as $val) {
                $style = explode(',', $val);
                $sfArray[] = array('title' => $style['0'], 'selector' => 'a,strong,em,p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,tr,span,img', 'classes' => $style['1']);
            }
        } else {
					$sfArray[] = array('title' => 'Paragraph', 'format' => 'p');
					$sfArray[] = array('title' => 'Header 1', 'format' => 'h1');
					$sfArray[] = array('title' => 'Header 2', 'format' => 'h2');
					$sfArray[] = array('title' => 'Header 3', 'format' => 'h3');
					$sfArray[] = array('title' => 'Header 4', 'format' => 'h4');
					$sfArray[] = array('title' => 'Header 5', 'format' => 'h5');
					$sfArray[] = array('title' => 'Header 6', 'format' => 'h6');
					$sfArray[] = array('title' => 'Div', 'format' => 'div');
					$sfArray[] = array('title' => 'Pre', 'format' => 'pre');
				}
        return $sfArray;    // return NULL would avoid bridging this parameter
    }
````

Might be nice to make this default (and then also add some usable styles as an example to the plugin-configuration as well!)

**Comment by janniconl** [comment]
P.s. even when you fix this, it is pretty unusable (only for adding classes to an element, besides it is badly configured).

If we want to make this work properly, it should support json strings (instead of exploding strings with pipes), so you can use a configuration like this:

```
[
    {title: 'Bold text', inline: 'b'},
    {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
    {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
    {title: 'Example 1', inline: 'span', classes: 'example1'},
    {title: 'Example 2', inline: 'span', classes: 'example2'},
    {title: 'Table styles'},
    {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
  ]
```

https://www.tinymce.com/docs/configure/content-formatting/#style_formats

**Comment by janniconl** [comment]
Tried some solutions to realise the above (trying to implement a config like: `{"title" : "Bold text", "inline" : "b"}, {"title" : "Red text", "inline" : "span", "styles" : { "color" : "#ff0000"}}`), but my PHP is really bad. So I gave up after a while after getting lost in json_encodes, $modx->parseProperties and what not haha.

Can anyone help me how I can add a config like mentioned above in bridge.tinymce4.inc.php / bridge_style_formats() function?

**Comment by Deesen** [comment]
Reg. $this->pluginParams['pluginStyleFormats'], it seems you are using an older config-string. The new one should begin with "&styleFormats=...", the old one began with "&pluginStyleFormats= ...".

**Comment by Deesen** [comment]
To make them work you can remove `function bridge_style_formats()` completely from `bridge.tinymce4.inc.php`, means the parameter "style_formats" gets not modified via PHP before parsing so it will be added exactly like you put it in your theme. For example

```
$this->set('style_formats', '[
  {title: "Bold text", inline: "b"},
  {title: "Red text", inline: "span", styles: {color: "#ff0000"}},
  {title: "Red header", block: "h1", styles: {color: "#ff0000"}},
  {title: "Example 1", inline: "span", classes: "example1"},
  {title: "Example 2", inline: "span", classes: "example2"},
  {title: "Table styles"},
  {title: "Table row 1", selector: "tr", classes: "tablerow1"}
]', 'json'); 
```

Please pay attention to use only " not ' for your JSON-string like above example.

![tiny](https://cloud.githubusercontent.com/assets/8569221/15479496/c729fdc4-2120-11e6-80ef-fd5eebfbabf5.png)

**Comment by janniconl** [comment]
> Reg. $this->pluginParams['pluginStyleFormats'], it seems you are using an older config-string. The new one should begin with "&styleFormats=...", the old one began with "&pluginStyleFormats= ...". 

Ah, thats it, thx! My files are from 27-04, last commit is from 16-04 so I didnt think of not being up-to-date. I guess I forgot to update/parse DocBlock inside the plugin during the last update.

**Comment by janniconl** [comment]
> To make them work you can remove function bridge_style_formats() completely from bridge.tinymce4.inc.php, means the parameter "style_formats" gets not modified via PHP before parsing so it will be added exactly like you put it in your theme. For example

That simple. Wish I knew that earlier haha, anyways works great. Isnt it a good idea to make this the default way of configuring custom styles? (instead of the configuration with pipes)

This can be closed though. Thx for the help.
