### ISSUE TITLE
Custom Block Formats don't work

### ISSUE THREAD

**Issue by pelargo** [extras-evolution/tinymce4-for-modx-evo#28]
MODX Evolution 1.2 / TinyMCE 4.3.7.2
http://take.ms/MF4Zg

**Comment by Deesen** [comment]
Yes the setting will be taken from user-settings. I need to add a checkbox in user-settings like "Use default" to avoid this issue.

**Comment by Deesen** [comment]
Totally confused... ;-)

**Comment by pelargo** [comment]
Thank you for your quick reply. I had not seen the Tiny4 user-settings

**Comment by Deesen** [comment]
https://github.com/modxcms/evolution/commit/6230c969d03a334c656ef2964fda9e8c6ebe27b7
